import {FLAGS} from '../assets/flags/flags';

export const currencyList = [
  {
    id: 1,
    symbol: '₴',
    label: 'Ukrainian hryvnia ',
    code: 'UAH',
    img: FLAGS.ukraine,
  },
  {
    id: 2,
    symbol: '$',
    label: 'United States Dollar ',
    code: 'USD',
    img: FLAGS.usa,
  },
  {
    id: 3,
    symbol: '€',
    label: 'Euro ',
    code: 'EUR',
    img: FLAGS.euro,
  },
  {
    id: 4,
    symbol: '$',
    label: 'Australian Dollar ',
    code: 'AUD',
    img: FLAGS.australia,
  },
  {
    id: 5,
    symbol: '.د.ب',
    label: 'Bahrain Dinar ',
    code: 'BHD',
    img: FLAGS.bahrain,
  },
  {
    id: 6,
    symbol: 'R$',
    label: 'Brazilian Real ',
    code: 'BRL',
    img: FLAGS.brazil,
  },
  {
    id: 7,
    symbol: '£',
    label: 'British Pound ',
    code: 'GBP',
    img: FLAGS.uk,
  },
  {
    id: 8,
    symbol: '$',
    label: 'Canadian Dollar ',
    code: 'CAD',
    img: FLAGS.canada,
  },
  {
    id: 9,
    symbol: '$',
    label: 'Chilean Peso ',
    code: 'CLP',
    img: FLAGS.chile,
  },
  {
    id: 10,
    symbol: '¥',
    label: 'Chinese Yuan ',
    code: 'CNY',
    img: FLAGS.china,
  },
  {
    id: 11,
    symbol: 'Kč',
    label: 'Czech Republic Koruna ',
    code: 'CZK',
    img: FLAGS.czech,
  },
  {
    id: 12,
    symbol: 'kr',
    label: 'Danish Krone ',
    code: 'DKK',
    img: FLAGS.denmark,
  },
  {
    id: 13,
    symbol: '$',
    label: 'Hong Kong Dollar ',
    code: 'HKD',
    img: FLAGS.hong,
  },
  {
    id: 14,
    symbol: 'Ft',
    label: 'Hungarian Forint ',
    code: 'HUF',
    img: FLAGS.hungary,
  },
  {
    id: 15,
    symbol: '₹',
    label: 'Indian Rupee ',
    code: 'INR',
    img: FLAGS.india,
  },
  {
    id: 16,
    symbol: '₪',
    label: 'Israeli Shekel ',
    code: 'ILS',
    img: FLAGS.israel,
  },
  {
    id: 17,
    symbol: '¥',
    label: 'Japanese Yen ',
    code: 'JPY',
    img: FLAGS.japan,
  },
  {
    id: 18,
    symbol: 'د.ا',
    label: 'Jordanian Dinar ',
    code: 'JOD',
    img: FLAGS.jordan,
  },
  {
    id: 19,
    symbol: 'Sh',
    label: 'Kenyan Shilling ',
    code: 'KES',
    img: FLAGS.kenya,
  },
  {
    id: 20,
    symbol: '₩',
    label: 'Korean Won ',
    code: 'KRW',
    img: FLAGS.korea,
  },
  {
    id: 21,
    symbol: 'د.ك',
    label: 'Kuwaiti Dinar ',
    code: 'KWD',
    img: FLAGS.kuwait,
  },
  {
    id: 22,
    symbol: '$',
    label: 'Mexican Peso ',
    code: 'MXN',
    img: FLAGS.mexico,
  },
  {
    id: 23,
    symbol: 'د.م.',
    label: 'Moroccan Dirham ',
    code: 'MAD',
    img: FLAGS.morocco,
  },
  {
    id: 24,
    symbol: '$',
    label: 'Namibian Dollar ',
    code: 'NAD',
    img: FLAGS.namibia,
  },
  {
    id: 25,
    symbol: '$',
    label: 'New Zealand Dollar ',
    code: 'NZD',
    img: FLAGS.zealand,
  },
  {
    id: 26,
    symbol: 'kr',
    label: 'Norwegian Krone ',
    code: 'NOK',
    img: FLAGS.norway,
  },
  {
    id: 27,
    symbol: 'ر.ع.',
    label: 'Omani Rial ',
    code: 'OMR',
    img: FLAGS.oman,
  },
  {
    id: 28,
    symbol: 'zł',
    label: 'Polish Zloty ',
    code: 'PLN',
    img: FLAGS.poland,
  },
  {
    id: 29,
    symbol: 'ر.ق',
    label: 'Qatari Rial ',
    code: 'QAR',
    img: FLAGS.qatar,
  },
  {
    id: 30,
    symbol: 'lei',
    label: 'Romanian Leu ',
    code: 'RON',
    img: FLAGS.romania,
  },
  {
    id: 31,
    symbol: '₽',
    label: 'Russian Ruble ',
    code: 'RUB',
    img: FLAGS.russia,
  },
  {
    id: 32,
    symbol: '﷼',
    label: 'Saudi Riyal ',
    code: 'SAR',
    img: FLAGS.arabia,
  },
  {
    id: 33,
    symbol: '$',
    label: 'Singapore Dollar ',
    code: 'SGD',
    img: FLAGS.singapore,
  },
  {
    id: 34,
    symbol: 'R',
    label: 'South African Rand ',
    code: 'ZAR',
    img: FLAGS.africa,
  },
  {
    id: 35,
    symbol: 'kr',
    label: 'Swedish Krona ',
    code: 'SEK',
    img: FLAGS.sweden,
  },
  {
    id: 36,
    symbol: 'Fr.',
    label: 'Swiss Franc ',
    code: 'CHF',
    img: FLAGS.switz,
  },
  {
    id: 37,
    symbol: '₣',
    label: 'Central Polynesian Franc ',
    code: 'XPF',
    img: FLAGS.polynesia,
  },
  {
    id: 38,
    symbol: '฿',
    label: 'Thai Baht ',
    code: 'THB',
    img: FLAGS.thailand,
  },
  {
    id: 39,
    symbol: 'د.ت',
    label: 'Tunisian Dinar ',
    code: 'TND',
    img: FLAGS.tunisia,
  },
  {
    id: 40,
    symbol: '₺',
    label: 'Turkish Lira ',
    code: 'TRY',
    img: FLAGS.turkey,
  },
  {
    id: 41,
    symbol: 'د.إ',
    label: 'UAE Dirham ',
    code: 'AED',
    img: FLAGS.uae,
  },
];
